cinema:
    resource: "@CinemaBundle/Controller/"
    type:     annotation
    prefix:   /

group:
    resource: "@GroupBundle/Controller/"
    type:     annotation
    prefix:   /groupB

user:
    resource: "@UsersBundle/Controller/"
    type:     annotation
    prefix:   /user

chat:
    resource: "@ChatBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin