# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app_chat.topic_sample_service:
        class: AppBundle\Topic\AppTopic
        tags:
          - { name: gos_web_socket.topic }