# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    fos_user.doctrine_registry:
        alias: doctrine

    mybox.form.registration:
        class: UsersBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type }

    sonata.admin.users:
            class: UsersBundle\Admin\UsersAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Administration", label: "Membres" }
            arguments:
                - ~
                - UsersBundle\Entity\User
                - ~
            calls:
                - [ setTranslationDomain, [UsersBundle]]