app_topic:
    channel: app/chat
    handler:
        callback: 'app.topic' #related to the getName() of your topic

app_rpc:
    channel: sample/{method}
    handler:
        callback: 'acme.rpc' #related to the getName() or your RPC service
    requirements:
        method:
            pattern: "[a-z_]+"
